[DOPS-771] Migrate GA jobs to CircleCI
matic-insurance/sidekiq-group pull request #10
Opened 2022-03-28 13:59 UTC by greykurotsuki

2022-03-28 14:37 UTC, pmatv requested changes

2022-03-28 14:37 UTC, pmatv commented on .circleci/config.yml
> +  sidekiq-group.build-pull-request:
@greykurotsuki, I believe you may use a single workflow for PR and master

2022-03-29 07:39 UTC, pmatv commented
@greykurotsuki, some checks have been waiting for the status. Please change Git repo settings by specifying proper PR checks.

2022-03-29 09:46 UTC, greykurotsuki commented
> @greykurotsuki, some checks have been waiting for the status. Please change Git repo settings by specifying proper PR checks.

Done

2022-03-29 11:18 UTC, volkorny approved these changes

2022-03-30 08:24 UTC, pmatv approved these changes

2022-03-30 08:24 UTC, pmatv commented on .circleci/config.yml
> +      - robocop:
Please rename it to `rubocop`

2022-03-30 15:35 UTC, volkorny submitted a review, later dismissed

2022-03-30 15:38 UTC, volkorny approved these changes

2022-03-30 15:38 UTC, merged